[package]
name = "deluxe"
version = "0.1.0"
edition = "2021"

[features]
default = ["proc-macro"]
proc-macro = ["syn/proc-macro"]

[dependencies]
once_cell = "1.13.0"
proc-macro2 = "1.0.38"
syn = { version = "1.0.96", features = ["full", "parsing"], default-features = false }
deluxe-core = { path = "./core", version = "0.1.0" }
deluxe-macros = { path = "./macros", version = "0.1.0" }

[dev-dependencies]
quote = "1.0.18"

[workspace]
members = ["core", "macros"]
